# Site settings
title: Левша Плюс. Пресс-формы и оснастка
title_general: Левша Плюс
email: levshaplus@inbox.ru
url: https://example.github.io
description: "От мечты до реальности. От идеи до воплощения. Производство и обслуживание технологической оснастки, штампов и пресс-форм."
baseurl: ""
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Левша Плюс

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: http://facebook.com
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
